defaults:
  - _self_

# Basic application configuration
app:
  name: "MLOps Template API"
  version: "1.0.0"
  environment: "production"

# API configuration
api:
  host: "0.0.0.0"
  port: 8000
  docs_url: "/docs"
  redoc_url: "/redoc"

# Paths configuration
paths:
  data_raw: "data/raw"
  data_processed: "data/processed"
  models_trained: "models/trained"
  logs_dir: "logs"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  console: true
