[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "analysis-template"
version = "0.1.0"
description = "A template for data analysis projects."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "analysis_template", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.9.0"}
rich = "^13.5.2"
mkdocs = "^1.5.2"
mkdocs-material = "^9.2.8"
pymdown-extensions = "^10.2.1"
radon = {version = "^5.1.0", optional = true}
pytest = {version = "^8.1.1", optional = true}
ruff = {version = "^0.3.2", optional = true}
bandit = {version = "^1.7.8", optional = true}
mypy = {version = "^1.8.0", optional = true}
polars = {version = "^1.30.0", optional = true}
asgi-lifespan = {version = "^2.1.0", optional = true}
httpx = {version = "^0.27.0", optional = true}
fastapi = {version = "^0.110.0", optional = true}
hydra-core = {version = "^1.3.2", optional = true}
pydantic-settings = {version = "^2.1.0", optional = true}
joblib = {version = "^1.3.2", optional = true}
numpy = {version = "^1.26.4", optional = true}
pytest-cov = {version = "^5.0.0", optional = true}
scikit-learn = {version = "^1.5.0", optional = true}
matplotlib = {version = "^3.9.0", optional = true}
pytest-asyncio = {version = "^0.23.7", optional = true}

[tool.poetry.extras]
dev = ["radon", "pytest", "ruff", "bandit", "mypy", "polars", "asgi-lifespan", "httpx", "fastapi", "hydra-core", "pydantic-settings", "joblib", "numpy", "pytest-cov", "scikit-learn", "matplotlib", "pytest-asyncio"]

[tool.poetry.scripts]
mlsys = "analysis_template.bootstrap:bootstrap"

[tool.isort]
profile = "black"
known_first_party = ["analysis_template"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
