[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "analysis-template"
version = "0.1.0"
description = "A template for data analysis projects."
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "analysis_template", from = "src"}]

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.9.0"}
rich = "^13.5.2"
mkdocs = "^1.5.2"
mkdocs-material = "^9.2.8"
pymdown-extensions = "^10.2.1"


[tool.poetry.scripts]
mlsys = "analysis_template.bootstrap:bootstrap"

[tool.isort]
profile = "black"
known_first_party = ["analysis_template"]
