[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mlsys-variations-template"
version = "0.1.0"
description = "A streamlined data science project template"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
dependencies = [
    "jupyterlab>=4.0.0",
    "matplotlib>=3.7.0",
    "polars>=0.19.0",
    "seaborn>=0.12.0",
    "scikit-learn>=1.3.0",
    "pytest>=7.4.0",
    "pytest-asyncio>=0.21.0",
    "ruff>=0.1.0",
    "pre-commit>=3.4.0",
    "python-dotenv>=1.0.0",
    "pyarrow>=20.0.0",
    "hydra-core>=1.3.0",
    "pydantic>=2.5.0",
    "pydantic-settings>=2.1.0",
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "python-multipart>=0.0.6",
    "httpx>=0.25.0",
]

[project.optional-dependencies]
dev = [
    "pytest-cov>=4.1.0",
    "pytest-xdist>=3.3.0",
    "black>=23.7.0",
    "mypy>=1.5.0",
]

[tool.ruff]
target-version = "py310"
line-length = 88

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501",    # Line too long
    "B008",    # Do not perform function calls in argument defaults
    "B904",    # Use raise ... from err
    "B027",    # Empty method in abstract base class
    "B017",    # Assert raises without specifying expected exception
    "F401",    # Imported but unused
    "E722",    # Do not use bare except
    "E741",    # Ambiguous variable name
    "E402",    # Module level import not at top of file
]

[tool.ruff.lint.isort]
known-first-party = ["mlsys_variations_template"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[tool.pytest.ini_options]
testpaths = ["tests", "workflows/tests"]
python_files = "test_*.py"
addopts = "--cov=src --cov-report=term-missing --cov-report=xml"
asyncio_mode = "auto"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true

[tool.hatch.build.targets.wheel]
packages = ["src"]

# Configuration settings that would typically be in config.yaml
[tool.mlsys_variations_template]

# Data paths
[tool.mlsys_variations_template.data_paths]
raw = "data/raw"
processed = "data/processed"
interim = "data/interim"
external = "data/external"

# Model paths
[tool.mlsys_variations_template.model_paths]
trained = "models/trained"
evaluation = "models/evaluation"

# Reporting paths
[tool.mlsys_variations_template.report_paths]
figures = "reports/figures"
tables = "reports/tables"
documents = "reports/documents"

# Logging configuration
[tool.mlsys_variations_template.logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
file = "logs/analysis.log"

# Default parameters for analysis
[tool.mlsys_variations_template.parameters]
random_seed = 42
test_size = 0.2
cv_folds = 5
