# conf/api/production.yaml
host: "0.0.0.0"
port: ${oc.env:API_PORT,8000}
workers: ${oc.env:API_WORKERS,4}
timeout: 30
max_request_size: 10485760  # 10MB

security:
  enable_cors: true
  cors_origins:
    - "https://your-frontend.com"
    - "https://admin.your-company.com"
  api_key_header: "X-API-Key"
  rate_limit_enabled: true
  rate_limits:
    predict: "100/minute"
    batch_predict: "10/minute"
    model_management: "20/minute"

models:
  auto_load: true
  model_directory: ${oc.env:MODEL_DIRECTORY,"models/trained"}
  max_models: 5
  model_timeout: 300
  lazy_loading: true

monitoring:
  enable_metrics: true
  metrics_endpoint: "/api/v1/metrics"
  health_endpoint: "/api/v1/health"
  log_requests: true
  prometheus_port: 9090

caching:
  enabled: true
  backend: "redis"
  redis_url: ${oc.env:REDIS_URL,"redis://localhost:6379"}
  default_ttl: 300
