name: Dependency Check

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install latest dependencies
        run: |
          uv pip install --system -r requirements-unpinned.txt
          uv pip install --system -e ".[dev]"

      - name: Run all checks
        id: run-checks
        run: |
          make all-checks
        continue-on-error: true

      - name: Create report
        run: |
          mkdir -p reports/dependency-reports
          REPORT_PATH="reports/dependency-reports/dependency-report-${{ github.run_id }}.md"
          if [[ ${{ steps.run-checks.outcome }} == 'success' ]]; then
            echo "## Dependency Check Report" > $REPORT_PATH
            echo "**Status:** Success :white_check_mark:" >> $REPORT_PATH
            echo "**Workflow Run:** [${{ github.workflow }}#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $REPORT_PATH
            echo "" >> $REPORT_PATH
            echo "All tests passed with the latest dependencies." >> $REPORT_PATH
            echo "" >> $REPORT_PATH
            echo "### :package: Dependencies Tested" >> $REPORT_PATH
            echo '```' >> $REPORT_PATH
            uv pip freeze --system >> $REPORT_PATH
            echo '```' >> $REPORT_PATH
          else
            echo "## Dependency Check Report" > $REPORT_PATH
            echo "**Status:** Failure :x:" >> $REPORT_PATH
            echo "**Workflow Run:** [${{ github.workflow }}#${{ github.run_number }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" >> $REPORT_PATH
            echo "" >> $REPORT_PATH
            echo "Tests failed with the latest dependencies." >> $REPORT_PATH
            echo "Please review the [workflow logs](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details." >> $REPORT_PATH
          fi

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-report
          path: reports/dependency-reports/
